version: '3'
services:

  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["sh", "-c", "cd sql/schema && goose postgres postgres://$DB_USER:$DB_PASS@db:$DB_PORT/$DB_NAME?sslmode=disable up && cd ../.. && sqlc generate && /myapp/bin/api"]

  db:
    image: postgres:14-alpine3.18
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    restart: always