version: '3'
services:

  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command:  ["sh", "-c", "/myapp/bin/migrate up && /myapp/bin/api"]

  db:
    image: postgres:14-alpine3.18
    environment:
      - POSTGRES_DB=myapp_db
      - POSTGRES_USER=myapp_user
      - POSTGRES_PASSWORD=myapp_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myapp_user -d myapp_db"]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always